/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fff8f5',
        'surface-dim': '#e1d8d4',
        'surface-bright': '#fff8f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fbf2ed',
        'surface-container': '#f5ece7',
        'surface-container-high': '#efe6e2',
        'surface-container-highest': '#e9e1dc',
        'on-surface': '#1e1b18',
        'on-surface-variant': '#444842',
        'inverse-surface': '#34302c',
        'inverse-on-surface': '#f8efea',
        outline: '#747872',
        'outline-variant': '#c4c8c0',
        'surface-tint': '#566155',
        primary: '#475347',
        'on-primary': '#ffffff',
        'primary-container': '#5f6b5e',
        'on-primary-container': '#deebdb',
        'inverse-primary': '#bdcaba',
        secondary: '#8e4d34',
        'on-secondary': '#ffffff',
        'secondary-container': '#fea98b',
        'on-secondary-container': '#793c24',
        tertiary: '#51504c',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#696863',
        'on-tertiary-container': '#eae8e2',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d9e6d6',
        'primary-fixed-dim': '#bdcaba',
        'on-primary-fixed': '#131e14',
        'on-primary-fixed-variant': '#3e4a3e',
        'secondary-fixed': '#ffdbcf',
        'secondary-fixed-dim': '#ffb59b',
        'on-secondary-fixed': '#380d00',
        'on-secondary-fixed-variant': '#71361f',
        'tertiary-fixed': '#e5e2dc',
        'tertiary-fixed-dim': '#c9c6c1',
        'on-tertiary-fixed': '#1c1c18',
        'on-tertiary-fixed-variant': '#474743',
        background: '#fff8f5',
        'on-background': '#1e1b18',
        'surface-variant': '#e9e1dc',
      },
      borderRadius: {
        'sm': '0.25rem',
        DEFAULT: '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'container-max': '1200px',
        'section-gap': '6rem',
        'element-gap': '1.5rem',
        'margin-mobile': '1.25rem',
        'margin-desktop': '2.5rem',
      },
      fontFamily: {
        brand: ['"Allura"', 'cursive'],
        display: ['"Playfair Display"', 'serif'],
        headline: ['"Playfair Display"', 'serif'],
        body: ['"Inter"', '"Assistant"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['clamp(2.5rem, 5vw, 4rem)', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['clamp(2rem, 4vw, 3rem)', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-md': ['clamp(1.5rem, 3vw, 2rem)', { lineHeight: '1.3', fontWeight: '500' }],
        'headline-sm': ['clamp(1.25rem, 2.5vw, 1.5rem)', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['0.875rem', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      boxShadow: {
        'soft': '0 4px 20px -2px rgba(86, 97, 85, 0.08)',
        'modal': '0 20px 40px -15px rgba(86, 97, 85, 0.12)',
      },
      keyframes: {
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(1.5rem)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.8s ease-out forwards',
        'fade-in': 'fade-in 0.6s ease-out forwards',
      },
    },
  },
  plugins: [],
}
